
CREATE VIEW NUBMER_OF_PULPITS
AS SELECT
	[FACULTY_NAME] AS [Наименование факультета],
	COUNT([PULPIT]) AS [Количество кафедр]
FROM PULPIT INNER JOIN FACULTY ON PULPIT.FACULTY=FACULTY.FACULTY
GROUP BY FACULTY_NAME