CREATE VIEW AUDITORIUMS
AS SELECT 
	AUDITORIUM AS [Код],
	AUDITORIUM_NAME AS [Наименование]
FROM AUDITORIUM
WHERE AUDITORIUM_TYPE LIKE'%ЛК%'
GO
SELECT * FROM AUDITORIUMS

INSERT AUDITORIUMS values('112', '112-4')