ALTER VIEW NUBMER_OF_PULPITS WITH SCHEMABINDING
AS SELECT 
	FACULTY.FACULTY_NAME AS [Наименование факультета],
	COUNT(PULPIT.PULPIT) AS [Количество кафедр]
FROM DBO.PULPIT INNER JOIN DBO.FACULTY ON PULPIT.FACULTY=FACULTY.FACULTY
GROUP BY FACULTY.FACULTY_NAME
