//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab09
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Met_MyBaseEntities : DbContext
    {
        public Met_MyBaseEntities()
            : base("name=Met_MyBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ПОКУПКИ> ПОКУПКИ { get; set; }
        public virtual DbSet<ТОВАР> ТОВАР { get; set; }
        public virtual DbSet<ФИРМА> ФИРМА { get; set; }
    }
}
