//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab09
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПОКУПКИ
    {
        public int Номер { get; set; }
        public string Название_товара { get; set; }
        public Nullable<int> Количество_купленных_товаров { get; set; }
        public Nullable<System.DateTime> Дата_покупки { get; set; }
        public string Покупатель { get; set; }
    
        public virtual ТОВАР ТОВАР { get; set; }
        public virtual ФИРМА ФИРМА { get; set; }
    }
}
