//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab09
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТОВАР
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТОВАР()
        {
            this.ПОКУПКИ = new HashSet<ПОКУПКИ>();
        }
    
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<float> Цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПОКУПКИ> ПОКУПКИ { get; set; }
    }
}
