---1--- 

SELECT F.FACULTY, P.PULPIT_NAME, PR.PROFESSION_NAME
FROM  FACULTY AS F, PULPIT AS P, PROFESSION AS PR
WHERE  F.FACULTY=P.FACULTY AND P.FACULTY=PR.FACULTY AND  PR.PROFESSION_NAME IN
	(SELECT PROFESSION_NAME FROM PROFESSION WHERE PROFESSION_NAME LIKE '%технологи%')


---2---

SELECT	F.FACULTY,	P.PULPIT_NAME, PR.PROFESSION_NAME
FROM	FACULTY AS F INNER JOIN PULPIT AS P ON F.FACULTY=P.FACULTY INNER JOIN PROFESSION AS PR ON P.FACULTY=PR.FACULTY
WHERE	PR.PROFESSION_NAME IN 
	(SELECT PROFESSION_NAME FROM PROFESSION WHERE PROFESSION_NAME LIKE '%технологи%')


---3---

SELECT  DISTINCT F.FACULTY AS [Факультет],
	P.PULPIT_NAME AS [Кафедра]	,
	PR.PROFESSION_NAME AS [Профессия]
FROM	 FACULTY AS F INNER JOIN PROFESSION AS PR ON PR.FACULTY=F.FACULTY INNER JOIN PULPIT AS P ON F.FACULTY=P.FACULTY	
WHERE	 PROFESSION_NAME LIKE '%технологи%'


---4---

SELECT  	A1.AUDITORIUM_NAME AS [Номер аудитории], 
	A1.AUDITORIUM_CAPACITY AS [Вместимость],
	A1.AUDITORIUM_TYPE AS [Тип аудитории]
FROM AUDITORIUM A1 

SELECT 
	A1.AUDITORIUM_TYPE AS [Тип аудитории],
	A1.AUDITORIUM_CAPACITY AS [Максимальная вместимость для типа],
	A1.AUDITORIUM_NAME AS [Номера аудиторий такой вместимости] 
FROM AUDITORIUM A1 
WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM A2 
WHERE A1.AUDITORIUM_TYPE=A2.AUDITORIUM_TYPE ORDER BY AUDITORIUM_CAPACITY DESC)

---5---

SELECT FACULTY_NAME  AS [Список факультетов, на которых нет ни одной кафедры] FROM FACULTY
WHERE NOT EXISTS 
(SELECT * FROM PULPIT WHERE FACULTY.FACULTY=PULPIT.FACULTY)

---6---

SELECT top 1 
(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECTS='ОАиП') [ОАиП],
(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECTS='СУБД')[СУБД],
(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECTS='БД')[БД]

---7---

-- Выбрать студентов, у которых самые лучшие оценки по предмету
SELECT P1.IDSTUDENT AS [Студент], P1.NOTE AS [Оценка], P1.SUBJECTS AS [Предмет]
FROM PROGRESS AS P1 
WHERE NOTE>=ALL(SELECT NOTE FROM PROGRESS AS P2 WHERE P1.SUBJECTS=P2.SUBJECTS)

---8---

-- Выбрать студентов, у которых оценка по предмету выше, чем у хоть кого
SELECT P1.IDSTUDENT AS [Студент], P1.NOTE AS [Оценка], P1.SUBJECTS AS [Предмет]
FROM PROGRESS AS P1 
WHERE NOTE>ANY(SELECT NOTE FROM PROGRESS AS P2 WHERE P1.SUBJECTS=P2.SUBJECTS)
