CREATE database UNIVER
--1
SELECT * FROM FACULTY;
--2
SELECT TEACHER, PULPIT	FROM TEACHER;
--3
SELECT TEACHER_NAME		FROM TEACHER 
						WHERE PULPIT = 'ИСиТ';
--4
SELECT TEACHER_NAME		FROM TEACHER 
						WHERE PULPIT = 'ИСиТ' OR PULPIT = 'ПОиСОИ';
--5
SELECT TEACHER_NAME		FROM TEACHER 
						WHERE PULPIT = 'ИСиТ' AND GENDER = 'ж';
--6
SELECT TEACHER_NAME [Имя преподавалеля] 
						FROM TEACHER 
						WHERE PULPIT = 'ИСиТ' AND GENDER != 'ж';
--7
SELECT DISTINCT PULPIT	FROM TEACHER;
--8
SELECT AUDITORIUM, AUDITORIUM_CAPACITY FROM AUDITORIUM
						ORDER BY AUDITORIUM_CAPACITY;
--9
SELECT DISTINCT TOP(2) AUDITORIUM_TYPE, AUDITORIUM_CAPACITY	FROM AUDITORIUM
						ORDER BY AUDITORIUM_CAPACITY DESC;
--10
SELECT DISTINCT SUBJECT	FROM PROGRESS
						WHERE NOTE BETWEEN 8 AND 10;
--11
SELECT DISTINCT SUBJECT	FROM SUBJECT
						WHERE PULPIT IN ('ЛЗиДВ','ПОиСОИ','ОВ');
--12
SELECT	PROFESSION_NAME [Наименование специальности],
		QUALIFICATION [Квалификация]
					 	FROM PROFESSION
						WHERE QUALIFICATION LIKE '%химик%';
--13
CREATE TABLE #FIO_DATE (
						NAME nvarchar(100),
						BDAY date
						);
INSERT INTO #FIO_DATE (NAME, BDAY)
						SELECT NAME, BDAY		
						FROM STUDENT;
SELECT *				FROM #FIO_DATE;