USE BSTU_BUGAENKO

SELECT * FROM FACULTY
GO

SELECT TEACHER, PULPIT FROM TEACHER
GO

SELECT TEACHER_NAME FROM TEACHER WHERE PULPIT='ИСиТ'
GO

SELECT TEACHER_NAME, PULPIT  FROM TEACHER WHERE PULPIT='ПОиСОИ' OR  PULPIT='ИСиТ'
GO

SELECT TEACHER_NAME  FROM TEACHER WHERE GENDER='ж'
GO

SELECT TEACHER_NAME AS [Имя преподавателя]  FROM TEACHER WHERE GENDER<>'ж' OR GENDER IS NULL
GO

SELECT DISTINCT PULPIT AS [KAF]  FROM TEACHER 
GO

SELECT  * FROM AUDITORIUM  ORDER BY AUDITORIUM_CAPACITY
GO

SELECT DISTINCT TOP(2) AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM  ORDER BY AUDITORIUM_CAPACITY DESC
GO

SELECT DISTINCT SUBJECTS, NOTE FROM PROGRESS WHERE NOTE BETWEEN 8 AND 10

SELECT SUBJECTS FROM SUBJECTS WHERE PULPIT IN('ЛЗиДВ', 'ПОиСОИ', 'ОВ' ) 

SELECT PROFESSION_NAME AS [Наименование специальности], QUALIFICATION AS [Квалификация] FROM PROFESSION WHERE QUALIFICATION LIKE '%химик%'

GO

CREATE table #vika
(FIO nvarchar(50), Date_Of_Birth date)
GO
INSERT INTO #vika (FIO, Date_Of_Birth)
SELECT NAME, BDAY FROM STUDENT
SELECT * FROM #vika
GO



